name: flow
channels:
    - https://conda.anaconda.org/kne 
#    - https://conda.anaconda.org/tlatorre 
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
    - soumith
dependencies:
    - python==3.5.2
    - numpy==1.13.3
    - scipy==1.1.0
    - path.py
    - python-dateutil
    - joblib==0.10.3
    - mako==1.0.7
    - ipywidgets==5.1.5
    - numba==0.38.1
    - flask==1.0.2
    - pybox2d==2.3.1post2
    - pygame==1.9.2a0
    - h5py==2.8.0
    - matplotlib==2.0.2
    - opencv3=3.1.0
    - scikit-learn==0.19.1
    - mpi4py==2.0.0
    - pandas==0.23.4
    - pip:
        - Pillow==4.2.1
        - pyprind==2.11.2
        - boto3==1.7.73
        - PyOpenGL==3.1.0
        - nose2==0.8.0
        - pyzmq==17.1.0
        - tqdm==4.24.0
        - msgpack-python==0.5.6
        - cached_property==1.4.3
        - line_profiler==2.1.2
        - cloudpickle==0.5.3
        - Cython==0.28.5
        - redis==2.10.6
        - keras==1.2.1
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
        - awscli==1.15.74
        - gym==0.10.5
        - pyglet==1.3.2
        - git+https://github.com/neocxi/prettytensor.git
        - jupyter==1.0.0
        - progressbar2==3.38.0
        - chainer==1.18.0
        - tensorflow==1.10.0
        - numpy-stl==2.2.0
        - nibabel==2.1.0
        - pylru==1.0.9
        - hyperopt==0.1
        - polling==0.3.0
        - lxml==4.2.4
        # RLLIB installs
        - six==1.11.0
        - redis==2.10.6
