name: flow

dependencies:
    - python==3.5.2
    - numpy==1.14.0
    - scipy==1.1.0
    - lxml==4.2.4
    - six==1.11.0
    - path.py
    - python-dateutil==2.7.3
    - tensorflow==1.10.0
    - cloudpickle==0.5.3
    - opencv
    - setuptools==39.1.0
    - pip:
        - gym==0.10.5
        - pyprind==2.11.2
        - nose2==0.8.0
        - cached_property
        - joblib==0.10.3
        - dill
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
